### ISSUE TITLE
Skills are cut off (namely the Managing skill) in the character tab when only having the Core & Colony Manager loaded.

### ISSUE THREAD

**Issue by Stealth103** [FluffierThanThou/RW_Manager#24]
Tested this with many mods loaded, just the core and Colony Manager, and with the Core, CCL, CCL Vanilla Tweaks and Colony Manager and all of them it did the same thing.
![charactertabcutoff](https://cloud.githubusercontent.com/assets/20715751/17235891/335a70a6-550a-11e6-980b-b259a408e5e5.jpg)

**Comment by FluffierThanThou** [comment]
Vanilla UI issue. Not fixing.
