### ISSUE TITLE
Pawn 'Character' tab is too short and cuts off the Management category.

### ISSUE THREAD

**Issue by Laruae** [FluffierThanThou/RW_Manager#31]
EDIT: Immediately after submitting I noticed a closed issue for the same thing, which noted that this is a vanilla UI issue. Sorry for not fully reading the closed issues, please feel free to ignore this ticket. Love your mods, keep doing what you do so well!

Currently, the 'Character' tab is too short and excludes around 1/2 of the Management category, making it difficult to easily check your character's management stat. Any way this tab can be expanded a bit in order to allow us to fully view this? 

Below is a screenshot of the in game UI which has this content partially cut off. This has occurred on both a smaller laptop monitor and a larger desktop monitor (1366 x 768 & 1920 x 1080, respectively) so I do not believe this is an issue with the screen size. Screenshot was taken with only the Management mod active, on version Alpha 15 (0.15.0).

![20160902121917_1](https://cloud.githubusercontent.com/assets/10898219/18210707/ddf7e62e-7107-11e6-8995-6cc8fd747c2e.jpg)

**Comment by FluffierThanThou** [comment]
this is a vanilla issue, and I'm not really willing to touch it because that would mean redefining the character tab. Doing that is both out of scope for this mod, and raises quite a few compatibility concerns.
