### ISSUE TITLE
Unchecks manual work priorties on load savegame

### ISSUE THREAD

**Issue by olizit** [FluffierThanThou/RW_Manager#33]
RimWorld version 0.14.1249
RW_Manager version 0.14.1.0

Manual priorities check under work tab is uncheck after load a savegame.
1. Rimworld is started quick with only Core, CCL and RW_Manager mods
2. Check Manual priorities check
3. Save the game.
4. Quit to main menu
5. Load savegame
6. Manual priorities is uncheck

**Comment by FluffierThanThou** [comment]
Turns out this is a CCL bug in A15
