### ISSUE TITLE
Mysteriously duplicating bills on workstations [sculptures?]

### ISSUE THREAD

**Issue by Karel-Kroeze** [FluffierThanThou/RW_Manager#4]
https://ludeon.com/forums/index.php?topic=16888.msg183071#msg183071

**Comment by Karel-Kroeze** [comment]
possibly related to #9

**Comment by TheGentzy** [comment]
Does not persist through saves. This will be a tough pickle...

**Comment by TheGentzy** [comment]
Sorta related: Mysteriously duplicating bills on Electonics Bench

![screenshot 248](https://cloud.githubusercontent.com/assets/7831879/11990286/a6e8a9fe-a9c8-11e5-8df9-79e41aca3ca9.png)

Note from the picture: 
1-I only asked for 250
2-Each time it makes 5
3-SO it should only tell my tables to due a sum of 50
4-I got 2 tables
5-each should do 25

Table A:
![screenshot 249](https://cloud.githubusercontent.com/assets/7831879/11990312/ee817eb2-a9c8-11e5-96a5-eda218f3b90e.png)

Table B:
![screenshot 250](https://cloud.githubusercontent.com/assets/7831879/11990316/f4ed9bfa-a9c8-11e5-9659-e1a20a5be2df.png)

Never asked for 625 electronic chips...

Another note: Asked for 100 circuits, every time it makes 2 of em'. So it should only set it to do 50 times, got  tables so it should have them do 25 each. NEVER asked for 250 circuits.

Both recipes have JUST (about ~8 in-game hours ago) been added to the manger. Tables been just built.

More data:
Savegame:
[Gentz Co M&M Facility Dupix.zip](https://github.com/Karel-Kroeze/RW_Manager/files/71479/Gentz.Co.M.M.Facility.Dupix.zip)

World:
[Rana.zip](https://github.com/Karel-Kroeze/RW_Manager/files/71480/Rana.zip)

Outlog:
[output_log.txt](https://github.com/Karel-Kroeze/RW_Manager/files/71481/output_log.txt)

**Comment by valuial** [comment]
I have duplicating, or rather multiplicating bills as well. But I found how to replicate the issue (I use a butcher table as example, seems to work with any table? have had it with the oven from the veggies mod as well as the cooking tables from vanilla)

1) start a new world with only core and the Manager as mods, new game
2) build Butcher and Manager tables, start hunting some small game, stockpile, dumping zone
3) Manager: create "butcher creature" task with all default values (values shouldn't matter)
4) have a pawn create the bill
5) accidentally delete the bill, you really need food though, so create the bill yourself (leave it as butcher 1x)
=> next time a pawn does the Management you start generating lots of identical bills.

**Comment by valuial** [comment]
Logfile and screenshot to go with the last post.
[logfile.txt](https://github.com/Karel-Kroeze/RW_Manager/files/213516/logfile.txt)
![billmultiplication](https://cloud.githubusercontent.com/assets/12469889/14436236/0fb919b0-001c-11e6-92da-54b2b12bb4ed.png)

**Comment by FluffierThanThou** [comment]
related? https://ludeon.com/forums/index.php?action=dlattach;topic=16888.0;attach=11926
